title: 夜ふかし郵便局(仮)
description: 思考とか日記とかについて考える
theme: minima
header_pages:
  - index.md
  - diary.md
  - loghapi-archive/index.md
defaults:
  - scope:
      path: "Diary"
      type: "pages"
    values:
      rss: true
